data:
  image: "busybox:latest"
  volumes:
    - /var/lib/rabbitmq
    - /data
    - /usr/src/app/data
rabbitmq:
  image: "rabbitmq:management"
  hostname: rabbitmq-dev
  expose:
    - "5672"
  ports:
    - "15672:15672"
    - "5672:5672"
  volumes_from:
    - data
mongo:
  image: "mongo:4.0.0"
  hostname: mongo-dev
  ports:
    - "27017:27017"
  volumes_from:
    - data
  command: mongod --smallfiles
redis:
  image: "redis:latest"
  hostname: redis-dev
  ports:
    - "6379:6379"
  volumes_from:
    - data
  command: redis-server --appendonly yes
